routes/web.php
<?php

use App\Http\Controllers\Admin\AdminPanelController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ParserController;
use App\Http\Controllers\WebsitesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/_aetos_admin', function() {
    return view('admin.auth.login');
})->name('login');

Route::post('/_aetos_admin', [AuthController::class, 'login']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::post('sets-of-website/add-data', [WebsitesController::class, 'store'])->name('admin.create_set_for_new_website');
Route::patch('sets-of-website/edit-data/{id}', [WebsitesController::class, 'update'])->name('admin.edit_set_for_website');
Route::delete('sets-of-website/delete/{id}', [WebsitesController::class, 'destroy'])->name('admin.delete_the_set');

Route::get('/admin', [AdminPanelController::class, 'showAdminPanel'])->name('admin');
Route::get('/admin/sets', [AdminPanelController::class, 'showAllSets'])->name('admin.sets');
Route::get('/admin/sets/create', [AdminPanelController::class, 'showFormToCreateSet'])->name('admin.set.create');
Route::get('/admin/sets/edit/{id}', [AdminPanelController::class, 'showFormToEditSet'])->name('admin.set.edit');
Route::get('/admin/sets/{id}', [AdminPanelController::class, 'showSingleSet'])->name('admin.set.show');

Route::resource('/admin/categories', CategoryController::class);

Route::get('/', [ArticleController::class, 'index'])->name('home');
Route::get('/articles', [ArticleController::class, 'allArticles'])->name('articles');
Route::get('/articles/filtered-by', [ArticleController::class, 'filterArticles'])->name('articles.filtered');
Route::get('/articles/{slug}', [ArticleController::class, 'show'])->name('articles.show');
Route::get('/categories', [ArticleController::class, 'allCategories'])->name('articles.all_categories');
Route::get('/offer', [ArticleController::class, 'handleSpecialPage'])->name('offer')->defaults('pageType', 'offer');
Route::get('/partners', [ArticleController::class, 'handleSpecialPage'])->name('partners')->defaults('pageType', 'partners');
Route::get('/recommendations', [ArticleController::class, 'handleSpecialPage'])->name('recommendations')->defaults('pageType', 'recommendations');

Route::get('weather', function() {
    return view('skill_up.weather');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'slug'
    ];

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }

    public function pages(): HasMany
    {
        return $this->hasMany(Page::class, 'category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Traits\Transliterable;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class CategoryController extends Controller
{
    use Transliterable;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('check.auth.session');
    }

    public function index()
    {
        $categories = Category::orderBy('name')->get();

        $h1 = 'Список категорий';
        $title = 'Список категорий';
        $breadcrumbs = [
            ['title' => 'Admin Panel', 'route' => route('admin')],
            ['title' => 'Список категорий', 'route' => null]
        ];

        return view('admin.categories.all_categories', compact('categories', 'h1', 'title', 'breadcrumbs'));
    }

    public function create()
    {
        $h1 = 'Создать категорию';
        $breadcrumbs = [
            ['title' => 'Admin Panel', 'route' => route('admin')],
            ['title' => 'All Categories', 'route' => route('categories.index')],
            ['title' => 'Create Category', 'route' => null]
        ];

        return view('admin.categories.create', compact('h1', 'breadcrumbs'));
    }

    public function store(Request $request): JsonResponse
    {
        try {
            $validatedData = $request->validate([
                'name' => 'required|unique:categories'
            ]);

            $slug = Str::slug($this->transliterable($request->name), '-');

            $validatedData['slug'] = $slug;

            $category = Category::create($validatedData);

            return response()->json(['success' => true, 'category' => $category]);
        } catch (ValidationException $e) {
            Log::info($e->errors());
            return response()->json(['success' => false, 'errors' => $e->errors()], 422);
        } catch (\Exception $e) {
            Log::info($e->getMessage());
            return response()->json(['success' => false, 'error' => $e->getMessage()], 500);
        }
    }

    public function show(Category $category)
    {
        $id = $category->id;
        $h1 = $title = $category->name;
        $breadcrumbs = [
            ['title' => 'Admin Panel', 'route' => route('admin')],
            ['title' => 'All Categories', 'route' => route('categories.index')],
            ['title' => $category->name, 'route' => null]
        ];

        return view('admin.categories.show', compact('category', 'h1', 'title', 'breadcrumbs', 'id'));
    }

    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    public function update(Request $request, Category $category): JsonResponse
    {
        try {
            $validatedData = $request->validate([
                'name' => 'required|unique:categories,name,' . $category->id
            ]);

            $slug = Str::slug($this->transliterable($request->name), '-');

            $slugExists = Category::where('slug', $slug)->where('id', '!=', $category->id)->exists();

            if ($slugExists) {
                return response()->json(['success' => false, 'message' => 'The category name generates a slug that already exists.'], 422);
            }

            $validatedData['slug'] = $slug;

            $category->update($validatedData);

            return response()->json(['success' => true, 'message' => 'Category updated successfully', 'category' => $category]);
        } catch (\Exception $e) {
            return response()->json(['success' => false, 'error' => $e->getMessage()], 500);
        }
    }

    public function destroy(Category $category): JsonResponse
    {
        try {
            $category->delete();
            return response()->json(['success' => true, 'message' => 'Category deleted successfully']);
        } catch (\Exception $e) {
            return response()->json(['success' => false, 'error' => $e->getMessage()], 500);
        }
    }
}

resources/views/admin/categories/all_categories.blade.php
@php
    use App\Constants\Constants;
    use Carbon\Carbon;
@endphp

@extends('admin.categories.index')

@section('title', $title)

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <table id="data-table" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th class="table-last-updated-column">{{ Constants::LAST_UPDATED }}</th>
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                @if(isset($category->id))
                                    <tr class="row-of-sets">
                                        <td><a href="{{ route('categories.show', ['category' => $category->id]) }}">{{ $category->name }}</a></td>
                                        <td class="table-last-updated-column">{{ Carbon::parse($category->updated_at)->format('d.m.Y в H:i:s') }}</td>
                                        <td class="table-column-with-button">
                                            <button type="button" class="btn btn-primary btn-primary edit-set" data-category-id="{{ $category->id }}">Редактировать</button>
                                        </td>
                                        <td class="table-column-with-button">
                                            <button type="button" class="btn btn-primary btn-danger delete-set" data-route="{{ route('categories.destroy', ['category' => $category->id]) }}">Удалить</button>
                                        </td>
                                    </tr>
                                @endif
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>Название</th>
                                <th class="table-last-updated-column">{{ Constants::LAST_UPDATED }}</th>
                                <th>&nbsp;</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->

            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
@endsection

resources/views/admin/categories/create.blade.php
<!DOCTYPE html>
<html lang="ru">

@include('../admin.head')

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    @include('../admin.header')
    @include('../admin.left_sidebar')

    <div class="content-wrapper">
        @include('../admin.breadcrumb')

        <section class="content">
            <div id="liveText">&nbsp;</div>
            <input type="text" id="categoryInput" placeholder="Введите название категории">
            <button id="saveButton">Сохранить</button>
            <div id="errorMessage" class="errorMessage"></div>

            <div id="categoryModal" class="modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body modal-text-button">
                            <p>Категория успешно добавлена</p><button id="okButton" type="button" class="btn button-modal-text btn-primary">OK</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        </section>
    </div>
</div>

@include('../admin.bottom')

<script>
    document.getElementById('categoryInput').addEventListener('input', function() {
        document.getElementById('liveText').innerText = this.value;
    });

    document.getElementById('saveButton').addEventListener('click', function() {
        const categoryName = document.getElementById('categoryInput').value;

        fetch('/admin/categories', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            body: JSON.stringify({ name: categoryName})
        })
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                const errorMessageElement = document.getElementById('errorMessage');
                errorMessageElement.style.display = "block";
                if (response.status === 422) {
                    return response.json().then(data => {
                        errorMessageElement.innerHTML = Object.values(data.errors).join('. ');
                    });
                } else {
                    errorMessageElement.innerHTML = 'Network response was not OK';
                }
            }
        })
        .then(data => {
            if(data && data.success) {
                document.getElementById('categoryModal').style.display = "block";
                document.getElementById('categoryInput').value = "";
                document.getElementById('liveText').innerHTML = "&nbsp;";
                const errorMessageElement = document.getElementById('errorMessage');
                errorMessageElement.style.display = "none";
                errorMessageElement.innerHTML = "";
            }
        });
    });

    document.getElementById('okButton').addEventListener('click', function() {
        document.getElementById('categoryModal').style.display = "none";
    });

    window.onclick = function(event) {
        const modal = document.getElementById('categoryModal');
        if (event.target === modal) {
            modal.style.display = "none";
        }
    }

</script>

</body>
</html>

resources/views/admin/categories/index.blade.php
<!DOCTYPE html>
<html lang="ru">

@section('title', 'Список категорий')
@include('../admin.head')

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    @include('../admin.header')
    @include('../admin.left_sidebar')

    <div class="content-wrapper">

        @include('../admin.breadcrumb')

        <section class="content">
            @yield('content')

            <script src="{{ asset('adminpanel_content/js/category-actions.js') }}"></script>
        </section>
    </div>
</div>

@include('../admin.bottom')

</body>
</html>

resources/views/admin/categories/show.blade.php
@extends('admin.categories.index')

@section('title', $title)

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body category-name">
                        {{ $title }}
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
                <div class="row">
                    <div class="col-xs-6">
                        <button class="btn btn-primary btn-lg custom-button-length edit-set" data-category-id="{{ $id }}">Редактировать</button>
                    </div>
                    <div class="col-xs-6 text-right">
                        <button class="btn btn-danger btn-lg custom-button-length delete-set" data-route="{{ route('categories.destroy', ['category' => $category->id]) }}">Удалить</button>
                        @php($urlForRedirect = route('admin.sets'))
                    </div>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->

        <script>
            let categoryOldName = @json($category->name);
        </script>
    </section><!-- /.content -->
@endsection